---
- name: Testing andrewrothstein.kots
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kots version'
      ansible.builtin.command: kots version
      changed_when: false
      register: kots_test_output
    - name: Output from 'kots version'
      ansible.builtin.debug:
        msg: '{{ kots_test_output.stdout }}'
