---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ kots_install_dir }}...
  become: true
  stat:
    path: '{{ kots_install_dir }}'
  changed_when: False
  register: kots_binary
- when: not kots_binary.stat.exists
  block:
    - name: downloading {{ kots_url }}...
      become: true
      become_user: root
      get_url:
        url: '{{ kots_url }}'
        dest: '{{ kots_tmp_archive }}'
        checksum: '{{ kots_checksum }}'
        mode: 0644
    - name: mkdir {{ kots_install_dir }}...
      become: true
      become_user: root
      file:
        path: '{{ kots_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ kots_tmp_archive }} to {{ kots_install_dir }}...
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ kots_tmp_archive }}'
        dest: '{{ kots_install_dir }}'
        creates: '{{ kots_install_dir }}/kots'
  always:
    - name: rm {{ kots_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ kots_tmp_archive }}'
        state: absent
- name: link executables in {{ kots_install_dir }} from {{ kots_parent_install_dir }}/bin...
  become: true
  become_user: root
  with_items:
    - kots
  file:
    src: '{{ kots_install_dir }}/{{ item }}'
    dest: '{{ kots_parent_install_dir }}/bin/{{ item }}'
    state: link
